plugins:
  - import

env:
  browser: true
  mocha: true
  node: true
  es6: true

rules:
  import/no-unresolved: 2
  comma-dangle:
    - 2
    - always-multiline
  indent:
    - 2
    - 2
    - SwitchCase: 1
  no-console: 1
  no-unused-expressions: 0
  no-underscore-dangle: 0
  consistent-return: 0
  no-shadow: 0
  max-len: 0
  prefer-template: 2
  no-use-before-define: 0
  newline-per-chained-call: 0
  global-require: 0
  arrow-body-style:
    - 2
    - as-needed
